# Site settings
title: Talking boy, talking ruby
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://talkingboy.com"
# Build settings
markdown: kramdown
permalink: pretty

# Sass support
sass:
  sass_dir: _sass
  style: :compressed
